In [ ]:
# loading in modules
import sqlite3
import pandas as pd
# creating file path
dbfile = 'logs_20220912.db'
dbfile2 = 'logs_20220913.db'
dbfile3 = 'logs_20220914.db'
# Create a SQL connection to our SQLite database
con = sqlite3.connect(dbfile)
con2 = sqlite3.connect(dbfile2)
con3 = sqlite3.connect(dbfile3)
# creating cursor
cur = con.cursor()
cur2 = con2.cursor()
cur3 = con3.cursor()

# reading all table names
table_list = [a for a in cur.execute("SELECT name FROM sqlite_master WHERE type = 'table'")]
# here is you table list
print(table_list)

In [ ]:

con = sqlite3.connect('logs_20220912.db')
cur = con.cursor()
events = []
for row in cur.execute("SELECT * FROM 'events'"):
      events.append(row)       
        
events = pd.DataFrame(events) 
events = events.set_index(0)
events.columns = ['forecastMarker','request_time','event_id','sender','context','session_id']
eve = events.drop(['context',], axis = 1)
eve

In [ ]:
event =[]
for row in cur.execute("SELECT * FROM 'event_name'"):
      event.append(row)   
event = pd.DataFrame(event) 
event = event.set_index(0)      
event.columns = ['event_name']

In [15]:

con2 = sqlite3.connect('logs_20220913.db')
cur2 = con2.cursor()
events2 = []
for row in cur2.execute("SELECT * FROM 'events'"):
      events2.append(row)       
        
events2 = pd.DataFrame(events2) 
events2 = events2.set_index(0)
events2.columns = ['forecastMarker','request_time','event_id','sender','context','session_id']
eve2 = events2.drop(['context',], axis = 1)
eve2

,forecastMarker,request_time,event_id,sender,session_id
0,,,,,
1,None,2022-09-13 00:10:27.967745,1,None,fa89a4d46b9b34761a580f0152f94f05
2,None,2022-09-13 00:10:27.972425,29,None,fa89a4d46b9b34761a580f0152f94f05
3,None,2022-09-13 00:10:27.977883,5,None,fa89a4d46b9b34761a580f0152f94f05
4,None,2022-09-13 00:10:27.982433,8,None,fa89a4d46b9b34761a580f0152f94f05
5,None,2022-09-13 00:10:27.989409,9,None,fa89a4d46b9b34761a580f0152f94f05
...,...,...,...,...,...
22271,weekly_report.SS:no_segment_users,2022-09-13 09:41:15.052806,24,test.weekly_report.ss,d637d1b6d2b70fd088e2ea44959483cb
22272,weekly_report.SS:no_segment_users,2022-09-13 09:41:15.058017,15,test.weekly_report.ss,d637d1b6d2b70fd088e2ea44959483cb
22273,weekly_report.SS:no_segment_users,2022-09-13 09:41:15.065892,16,test.weekly_report.ss,d637d1b6d2b70fd088e2ea44959483cb
22274,weekly_report.SS:no_segment_users,2022-09-13 09:41:15.071837,17,test.weekly_report.ss,d637d1b6d2b70fd088e2ea44959483cb
22275,weekly_report.SS:no_segment_users,2022-09-13 09:41:15.078643,31,test.weekly_report.ss,d637d1b6d2b70fd088e2ea44959483cb

In [16]:

con3 = sqlite3.connect('logs_20220914.db')
cur3 = con3.cursor()
events3 = []
for row in cur3.execute("SELECT * FROM 'events'"):
      events3.append(row)       
        
events3 = pd.DataFrame(events3) 
events3 = events3.set_index(0)
events3.columns = ['forecastMarker','request_time','event_id','sender','context','session_id']
eve3 = events3.drop(['context',], axis = 1)
eve3

,forecastMarker,request_time,event_id,sender,session_id
0,,,,,
1,None,2022-09-14 00:09:39.234361,1,None,ec6a82e4a1b9b4dc467639eb1a5d6987
2,None,2022-09-14 00:09:39.238851,29,None,ec6a82e4a1b9b4dc467639eb1a5d6987
3,None,2022-09-14 00:09:39.242626,5,None,ec6a82e4a1b9b4dc467639eb1a5d6987
4,None,2022-09-14 00:09:39.248606,8,None,ec6a82e4a1b9b4dc467639eb1a5d6987
5,None,2022-09-14 00:09:39.254990,9,None,ec6a82e4a1b9b4dc467639eb1a5d6987
...,...,...,...,...,...
11245,weekly_report.SS:new_users_90d:tiktok,2022-09-14 06:07:47.582138,24,weekly_report.ss,7caa7e3d9378310a86ce7e20fc58b561
11246,weekly_report.SS:new_users_90d:tiktok,2022-09-14 06:07:47.588185,15,weekly_report.ss,7caa7e3d9378310a86ce7e20fc58b561
11247,weekly_report.SS:new_users_90d:tiktok,2022-09-14 06:07:47.594110,16,weekly_report.ss,7caa7e3d9378310a86ce7e20fc58b561
11248,weekly_report.SS:new_users_90d:tiktok,2022-09-14 06:07:47.601623,17,weekly_report.ss,7caa7e3d9378310a86ce7e20fc58b561
11249,weekly_report.SS:new_users_90d:tiktok,2022-09-14 06:07:47.609898,31,weekly_report.ss,7caa7e3d9378310a86ce7e20fc58b561

In [17]:
 # Be sure to close the connection
con.close()
print("соединение закрыто")

соединение закрыто